### ISSUE TITLE
Is it possible to share the overlay layer?

### ISSUE THREAD

**Issue by YangWang92** [zhutmost/edgeboard#3]
Hi, 

Thanks for sharing such an interesting project. I have confirmed that your prebuild image works on my FZ3B board but only with 2GB memory.

However, I found that FZ3B owns 4GB DRAM on the PS side. I would like to support PYNQ on FZ3B. 

Can you share the overlay layer source codes, which can be compiled to bitstream for FZ3A? 

I would like to improve the source codes to support FZ3B. Thanks a lot!

**Comment by zhutmost** [comment]
I do not know what "overlay layer source code" refers to. 

I think, to port to FZ3B with larger DRAM, you just need to rebuild a BSP file (including the corresponding board design)?

**Comment by YangWang92** [comment]
Thanks for your advice, I'm trying to port a new BSP file.
