### ISSUE TITLE
文中提到的FZ3B镜像启动失败

### ISSUE THREAD

**Issue by KenMax233** [zhutmost/edgeboard#7]
我用到您提供的FZ3B镜像文件，用一张32g tf卡烧录系统，卡在了内核恐慌

[    4.221798] xilinx-zynqmp-dma fd530000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.229909] xilinx-zynqmp-dma fd540000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.238017] xilinx-zynqmp-dma fd550000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.246123] xilinx-zynqmp-dma fd560000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.254232] xilinx-zynqmp-dma fd570000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.262408] xilinx-zynqmp-dma ffa80000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.270520] xilinx-zynqmp-dma ffa90000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.278630] xilinx-zynqmp-dma ffaa0000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.286742] xilinx-zynqmp-dma ffab0000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.294857] xilinx-zynqmp-dma ffac0000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.302972] xilinx-zynqmp-dma ffad0000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.311086] xilinx-zynqmp-dma ffae0000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.319196] xilinx-zynqmp-dma ffaf0000.dma-controller: ZynqMP DMA driver Prob                                                               e success

[    4.327563] xilinx-zynqmp-dpdma fd4c0000.dma-controller: Xilinx DPDMA engine                                                                is probed

[    4.335689] xilinx-psgtr fd400000.phy: Invalid reference clock number 2

[    4.342313] zynqmp-display fd4a0000.display: failed to get PHY lane 0

[    4.348793] zynqmp-display: probe of fd4a0000.display failed with error -22

[    4.356672] zynqmp-qspi ff0f0000.spi: rx bus width not found

[    4.362338] zynqmp-qspi ff0f0000.spi: tx bus width not found

[    4.368094] spi_master spi0: cannot find modalias for /axi/spi@ff0f0000/flash                                                               @0

[    4.375418] spi_master spi0: Failed to create SPI device for /axi/spi@ff0f000                                                               0/flash@0

[    4.383914] xilinx_can ff070000.can can0: TDC Offset value not in range

[    4.390930] macb ff0e0000.ethernet: Not enabling partial store and forward

[    4.401519] macb ff0e0000.ethernet eth0: Cadence GEM rev 0x50070106 at 0xff0e                                                               0000 irq 39 (a6:c9:15:21:51:6c)

[    4.411671] xilinx-axipmon ffa00000.perf-monitor: Probed Xilinx APM

[    4.418226] xilinx-axipmon fd0b0000.perf-monitor: Probed Xilinx APM

[    4.424746] xilinx-axipmon fd490000.perf-monitor: Probed Xilinx APM

[    4.431267] xilinx-axipmon ffa10000.perf-monitor: Probed Xilinx APM

[    4.459776] cdns-i2c ff020000.i2c: 400 kHz mmio ff020000 irq 41

[    4.466826] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller

[    4.472336] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus nu                                                               mber 1

[    4.472400] cdns-i2c ff030000.i2c: 400 kHz mmio ff030000 irq 42

[    4.480094] xhci-hcd xhci-hcd.1.auto: hcc params 0x0238f625 hci version 0x100                                                                quirks 0x0000000002010010

[    4.486413] cpufreq: cpufreq_online: CPU0: Running at unlisted initial freque                                                               ncy: 1066666 KHz, changing to: 1199999 KHz

[    4.495327] xhci-hcd xhci-hcd.1.auto: irq 62, io mem 0xfe200000

[    4.514957] of_cfs_init

[    4.517483] of_cfs_init: OK

[    4.520399] cfg80211: Loading compiled-in X.509 certificates for regulatory d                                                               atabase

[    4.528410] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bc                                                               dDevice= 5.15

[    4.536694] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                               1

[    4.540422] mmc0: SDHCI controller on ff160000.mmc [ff160000.mmc] using ADMA                                                                64-bit

[    4.540648] mmc1: SDHCI controller on ff170000.mmc [ff170000.mmc] using ADMA                                                                64-bit

[    4.543935] usb usb1: Product: xHCI Host Controller

[    4.564117] usb usb1: Manufacturer: Linux 5.15.19-xilinx-v2022.1 xhci-hcd

[    4.570905] usb usb1: SerialNumber: xhci-hcd.1.auto

[    4.576302] hub 1-0:1.0: USB hub found

[    4.580192] hub 1-0:1.0: 1 port detected

[    4.584346] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller

[    4.589856] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus nu                                                               mber 2

[    4.597537] xhci-hcd xhci-hcd.1.auto: Host supports USB 3.0 SuperSpeed

[    4.604236] usb usb2: We don't know the algorithms for LPM for this host, dis                                                               abling LPM.

[    4.612608] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bc                                                               dDevice= 5.15

[    4.620890] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=                                                               1

[    4.628126] usb usb2: Product: xHCI Host Controller

[    4.633002] usb usb2: Manufacturer: Linux 5.15.19-xilinx-v2022.1 xhci-hcd

[    4.639790] usb usb2: SerialNumber: xhci-hcd.1.auto

[    4.645012] hub 2-0:1.0: USB hub found

[    4.648884] hub 2-0:1.0: 1 port detected

[    4.679867] mmc1: new high speed SDHC card at address b368

[    4.685763] mmcblk1: mmc1:b368 NCard 29.1 GiB

[    4.689933] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'

[    4.692032]  mmcblk1: p1 p2

[    4.696744] clk: Not disabling unused clocks

[    4.704030] ALSA device list:

[    4.706998]   No soundcards found.

[    4.710701] platform regulatory.0: Direct firmware load for regulatory.db fai                                                               led with error -2

[    4.719333] cfg80211: failed to load regulatory.db

[    4.719383] mmc0: new HS200 MMC card at address 0001

[    4.729495] mmcblk0: mmc0:0001 Q2J55L 7.09 GiB

[    4.735603] mmcblk0boot0: mmc0:0001 Q2J55L 16.0 MiB

[    4.741568] mmcblk0boot1: mmc0:0001 Q2J55L 16.0 MiB

[    4.747355] mmcblk0rpmb: mmc0:0001 Q2J55L 4.00 MiB, chardev (240:0)

[    4.755884] EXT4-fs (mmcblk1p2): mounted filesystem with ordered data mode. O                                                               pts: (null). Quota mode: none.

[    4.765682] VFS: Mounted root (ext4 filesystem) on device 179:2.

[    4.779477] devtmpfs: mounted

[    4.782992] Freeing unused kernel memory: 2176K

[    4.787648] Run /sbin/init as init process

[    4.844920] usb 1-1: new high-speed USB device number 2 using xhci-hcd

[    4.998149] usb 1-1: New USB device found, idVendor=05e3, idProduct=0610, bcd                                                               Device=32.98

[    5.006348] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0

[    5.013488] usb 1-1: Product: USB2.0 Hub

[    5.052410] hub 1-1:1.0: USB hub found

[    5.056468] hub 1-1:1.0: 4 ports detected

[    5.064396] random: fast init done

/sbin/init: error while loading shared libraries: /lib/aarch64-li[    5.092012]                                                                Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00

[    5.105257] CPU: 0 PID: 1 Comm: init Not tainted 5.15.19-xilinx-v2022.1 #1

[    5.112126] Hardware name: xlnx,zynqmp (DT)

[    5.116301] Call trace:

[    5.118738]  dump_backtrace+0x0/0x190

[    5.122402]  show_stack+0x18/0x30

[    5.125709]  dump_stack_lvl+0x7c/0xa0

[    5.129363]  dump_stack+0x18/0x34

[    5.132670]  panic+0x14c/0x30c

[    5.135716]  do_exit+0x8dc/0x930

[    5.138937]  do_group_exit+0x38/0xa0

[    5.142504]  __arm64_sys_exit_group+0x18/0x20

[    5.146854]  invoke_syscall+0x54/0x124

[    5.150594]  el0_svc_common.constprop.0+0x44/0xfc

[    5.155291]  do_el0_svc+0x48/0xb0

[    5.158597]  el0_svc+0x28/0x80

[    5.161644]  el0t_64_sync_handler+0xa4/0x130

[    5.165906]  el0t_64_sync+0x1a0/0x1a4

[    5.169562] SMP: stopping secondary CPUs

[    5.173481] Kernel Offset: disabled

[    5.176956] CPU features: 0x00001001,00000842

[    5.181305] Memory Limit: none

[    5.184354] ---[ end Kernel panic - not syncing: Attempted to kill init! exit                                                               code=0x00007f00 ]---

nux-gnu/libaudit.so.1: invalid ELF header

**Comment by KenMax233** [comment]
问题是不能通过Win32DiskImager进行烧录，对分块有影响，还是得在ubuntu中烧录，感谢大佬开源并更新v3.0.1版本的镜像，我是小白，之前按照CSDN的方法花了两周来做，都失败了，看到您的博客才豁然开朗，谢谢！

**Comment by zhutmost** [comment]
Congratulations!
